### ISSUE TITLE
LabeldPoint position is fixed

### ISSUE THREAD

**Issue by aldefy** [stephanenicolas/RoboDemo#7]
I have used 

LabeledPoint p = new LabeledPoint( b, "Events: This is where all events and check-in happen" );
             arrayListPoints.add( p );
             p = new LabeledPoint(this,0.95f, 0.05f,"Use the Menu");
             arrayListPoints.add( p );

Where b is a button;

but all my demo labeled points are defaulted to left hand side top corner of my activity what i'm a doing wrong.
Edit :  calling my displaydemo in my onStart then also tried in oncreate

the "use the menu" is correct in its position, now for the fun part of this issue or my mistake:

when i inflate the overflow menu in my class with show demo again called  its position is spot on 

Please help

**Comment by aldefy** [comment]
Found my own solution 

For any one struggling 

when u call the displaydemoifneeded method in onCreate put it like this : 

new Handler().postDelayed( new Runnable() {
            @Override
            public void run() {
                displayDemoIfNeeded();
            }
        }, 500 ); 

instead of simply calling  displayDemoIfNeeded();

**Comment by ericharlow** [comment]
A suggestion instead of a handler try this in your activities onCreate.

```
private void displayDemoOnLayout(int resourceId) {
    final View v = findViewById(resourceId);
    v.getViewTreeObserver().addOnGlobalLayoutListener(new OnGlobalLayoutListener() {

        @Override
        public void onGlobalLayout() {
            showDemoIfNeeded();
            v.getViewTreeObserver().removeOnGlobalLayoutListener(this);
        }
    });
}
```
